config/routes.rb
Usstfruit::Application.routes.draw do
  devise_for :users
  mount WeixinRailsMiddleware::Engine, at: "/"
  mount Usstfruit::API => "/"
  
  namespace :mobile do
    root :to => 'products#index'
    get "two",:controller=>:home,:action=>:test
    resources :products
    resources :articles
    
    #shopping part
    resources :carts
    resources :cart_items do
      collection do
        get 'plus'
        get 'minus'
      end
    end
    resources :shoppings
    resources :weixin_users do
      member do 
        get 'history_shopping'
      end
    end
    
 end
 
 namespace :admin do
   root :to => 'home#index'
   
   resources :weixin_users
   
   resources :products do
     member do
       get 'on_sale'
       get 'off_sale'
     end
   end
   
   resources :product_cates
   resources :shoppings do
     member do
       get 'to_cancel'
       get 'to_confirm'
       get 'to_ship'
       get 'to_finish'
       
       get 'operation_history'
       
       put 'update_field'
       
       
       get 'daily_result'
     end
   end
   
   resources :articles
   resources :article_cates
   resources :users
   
   resources :pictures do
     collection do
       post 'upload'
     end
   end
 end
end

app/models/shopping.rb
class Shopping < ActiveRecord::Base
  include AASM
  has_many :shopping_items,:dependent => :destroy
  belongs_to :cart
  after_create :save_shopping_items,:create_notification
  before_save :update_status
  validates :customer_name,:customer_address,:mobile,:presence => true
  
  SHIP_ITEMS = []


   aasm do
     state :new, :initial => true
     state :confirmed
     state :shipping
     state :finished
     state :canceled
     
     event :confirm do
       transitions :from => :new, 
                    :to => :confirmed,:on_transition => :confirm_shopping
     end
     
     event :ship do
       transitions :from => :confirmed, 
                    :to => :shipping,:on_transition => :shipping_shopping
     end
     
     event :finish do
       transitions :from => :shipping, 
                    :to => :finished,:on_transition => :finish_shopping
     end
     
     
     event :cancel do
       transitions :from => [:new,:confirmed,:shipping,:finished], 
                   :to => :canceled,:on_transition => :cancel_shopping
     end
     
     
   end



  
  
  def confirm_shopping
    self.confirmed_at = Time.now
  end
  
  def shipping_shopping
    self.shipped_at = Time.now
  end
  
  
  def finish_shopping
    self.closed_at = Time.now
  end
  

  
  def cal_amount
    self.amount = self.shopping_items.inject(0) { |sum, i| sum+i.amount }
  end
  
  def cancel_shopping
    self.canceled_at = Time.now
  end
    

  
  def save_shopping_items
    shopping_items.each do |item|
      item.save
    end
  end
  
  
  def create_notification
    notification = Notification.new
    notification.content = "订单编号#{self.id},金额#{self.amount.to_f}被客户创建"
    notification.notifyable_type = "Shopping"
    notification.notifyable_id = self.id
    notification.save
  end
  
  def update_status
    if self.aasm_state == "new"
      self.status = "新订单"
    elsif self.aasm_state == "confirmed"
      self.status = "配货中"

    elsif self.aasm_state == "shipping"
      self.status = "配送中"

    elsif self.aasm_state == "finished"
      self.status = "订单完成"
    elsif self.aasm_state == "canceled"
      self.status = "订单取消"
    end

  end
  
end

app/controllers/admin/shoppings_controller.rb
class Admin::ShoppingsController <  Admin::BaseController
  def index
    @q = Shopping.search(params[:q])
    @shoppings = @q.result(distinct: true).order("created_at desc")
    @shoppings_grid = initialize_grid(@shoppings,:per_page => 50)
  end
  
  def show
    @shopping = Shopping.find(params[:id])
  end
  
  def operation_history
    @shopping = Shopping.find(params[:id])
  end
  
  def update_field
    @shopping=Shopping.find(params[:id])
    name = params[:name]
    value = params[:value]
    @shopping.update({name=>value})
    render :status=>200, :json=> {:message=>"OK"}
  end
  
  
  
  def destroy
    @shopping = Shopping.find(params[:id])
    @shopping.destroy
    redirect_to admin_shoppings_path,:notice=>"删除订单成功"
  end
  
  def to_confirm
    @shopping = Shopping.find(params[:id])
    @shopping.confirm
    @shopping.save
    respond_to do |format|
      format.html { redirect_to [:admin,@shopping],:notice=>"订单已确认配货" }
      format.js { render 'process' }
    end
    
  end
  
  
  def to_ship
    @shopping = Shopping.find(params[:id])
    @shopping.ship
    @shopping.save
    respond_to do |format|
      format.html {redirect_to [:admin,@shopping],:notice=>"订单已确认配货" }
      format.js { render 'process' }
    end
  end
  
  def to_finish
    @shopping = Shopping.find(params[:id])
    @shopping.finish
    @shopping.save
    respond_to do |format|
      format.html {redirect_to [:admin,@shopping],:notice=>"订单已确认配货" }
      format.js { render 'process' }
    end
  end
  def to_cancel
    @shopping = Shopping.find(params[:id])
    @shopping.cancel
    @shopping.save
    respond_to do |format|
      format.html {redirect_to [:admin,@shopping],:notice=>"订单已被取消" }
      format.js { render 'process' }
    end
  end
end

app/controllers/mobile/shoppings_controller.rb
class  Mobile::ShoppingsController < Mobile::BaseController  
  def index
  end
  
  def show
    @shopping = Shopping.find(params[:id])
  end
  
  def create
    @shopping = Shopping.new(shopping_params)
    
    logger.info("new shopping from cart id :#{@shopping.cart_id}")
    @cart = Cart.find(@shopping.cart_id)
    
    @cart.cart_items.each do |cart_item|
      if cart_item.quantity > 0 && cart_item.product.on_sale?
        shopping_item = ShoppingItem.new
        shopping_item.product_id = cart_item.product_id
        shopping_item.no  = cart_item.no
        shopping_item.name  = cart_item.name
        shopping_item.price  = cart_item.price
        shopping_item.unit = cart_item.try(:product).try(:unit)
        shopping_item.quantity  = cart_item.quantity
        shopping_item.amount  = cart_item.amount
        @shopping.shopping_items << shopping_item
      end
    end
    @shopping.cal_amount
    @shopping.weixin_user_id = current_weixin_user_id
    if @shopping.save
      session[:cart_id]=nil
      redirect_to history_shopping_mobile_weixin_user_path(current_weixin_user_id)
    else
      render 'new'
    end
  end
  
  
  def new
    if params[:cart_id].present? 
      @shopping = Shopping.new
      @shopping.cart_id = params[:cart_id]
      
      @cart = Cart.find(@shopping.cart_id)
      
      if @cart.check_any_off_sale?
        redirect_to edit_mobile_cart_path(@cart)
      end
      
      @shopping.remark = @cart.remark

    else
      redirect_to mobile_products_path
    end
  end
  
  private
  def shopping_params
    params.require(:shopping).permit!
  end
end

app/views/admin/shoppings/_grid.html.erb
<%= grid(@shoppings_grid, show_filters: :when_filtered, hide_csv_button: true) do |g|
	g.column :name => 'ID', :attribute => 'id' do |shopping|
		link_to shopping.id,[:admin,shopping]
	end
	g.column :name => '姓名', :attribute => 'customer_name'
	g.column :name => '地址', :attribute => 'customer_address'
	g.column :name => '手机', :attribute => 'mobile'
	g.column :name => '金额', :attribute => 'amount'
	g.column :name => '预计收货时间', :attribute => 'want_ship'
	g.column :name => '状态', :attribute => 'status' do  |shopping|
		raw "<div id=\"shopping_status_#{shopping.id}\"> #{shopping.status}</div>"
	end
	

	g.column do |shopping|
		render 'grid_ops',:shopping=>shopping
	end
	g.column do |shopping|
		link_to "删除",[:admin,shopping],:method=>:delete,:class=>"btn btn-danger"
	end
	
	
end -%>

app/views/admin/shoppings/_grid_ops.html.erb
<div id="shopping_<%=shopping.id%>" class="btn-group">  
	<%if shopping.may_confirm? %>
		<%=link_to "配货确认",to_confirm_admin_shopping_path(shopping),:class=>"btn btn-primary",:remote=>true%>
	<%end%>

	<%if shopping.may_ship? %>
		<%=link_to "送货确认",to_ship_admin_shopping_path(shopping),:class=>"btn btn-primary",:remote=>true%>
	<%end%>

	<%if shopping.may_finish? %>
		<%=link_to "订单完成",to_finish_admin_shopping_path(shopping),:class=>"btn btn-success",:remote=>true%>
	<%end%>

	<%if shopping.may_cancel? %>
		<%=link_to "取消",to_cancel_admin_shopping_path(shopping),:class=>"btn btn-danger",:remote=>true%>
	<%end%>
</div>

app/views/admin/shoppings/_header_nav.html.erb
<%= render_list :class => "nav nav-pills" do |li|
     li << link_to(t("基本信息"), [:admin,@shopping])
     li << link_to(t("操作信息"), operation_history_admin_shopping_path(@shopping))
end %>

app/views/admin/shoppings/_operation_buttons.html.erb
<div class="row">
	<div class="btn-group pull-left">
		<%=link_to "返回列表", admin_shoppings_path,:class=>"btn"%>
	
	</div>
	<div class="btn-group pull-right">
		<%if @shopping.may_cancel? %>
			<%=link_to "取消订单",to_cancel_admin_shopping_path(@shopping),:class=>"btn btn-danger"%>
		<%end%>
		<%if @shopping.may_confirm? %>
			<%=link_to "配货确认",to_confirm_admin_shopping_path(@shopping),:class=>"btn btn-primary"%>
		<%end%>

		<%if @shopping.may_ship? %>
			<%=link_to "送货确认",to_ship_admin_shopping_path(@shopping),:class=>"btn btn-primary"%>
		<%end%>
		
		<%if @shopping.may_finish? %>
			<%=link_to "订单完成",to_finish_admin_shopping_path(@shopping),:class=>"btn btn-success"%>
		<%end%>
		
		<%=link_to "删除",[:admin,@shopping],:method=>:delete,:class=>"btn btn-danger"%>
	</div>
</div>

app/views/admin/shoppings/index.html.erb
<div class="box">
	<div class="box-header">
	   <h3 class="box-title">客户订单列表</h3>
		 <div class="box-tools">
		 	<ul class="pagination pagination-sm no-margin pull-right">
       <li>
       	<%=link_to new_admin_shopping_path do%>
					<i class="fa fa-plus">新建</i>
				<%end%>
       </li>
     	</ul>
     </div>
	</div><!-- /.box-header -->
	<div class="box-body">
		<%=render 'grid'%>
	</div>
</div>

app/views/admin/shoppings/operation_history.html.erb
<%= content_for :title do %>
	订单详细信息 #<%=@shopping.id%>  
<% end %>

<%=render 'header_nav'%>

<div class=' box'>
	<div class='box-body'>
		<table class="table">
			<tr>
				<th>操作</th>
				<th>时间</th>
			</tr>
			
			<tr>
				<td>客户下单</td>
				<td><%=l @shopping.created_at if @shopping.created_at%></td>
			</tr>
			<tr>
				<td>确认配货</td>
				<td><%=l @shopping.confirmed_at if @shopping.confirmed_at%></td>
			</tr>
			<tr>
				<td>配送配送</td>
				<td><%=l @shopping.shipped_at if @shopping.shipped_at%></td>
			</tr>
			<tr>
				<td>完成订单</td>
				<td><%=l @shopping.closed_at if @shopping.closed_at%></td>
			</tr>
			<tr>
				<td>取消订单</td>
				<td><%=l @shopping.canceled_at if @shopping.canceled_at%></td>
			</tr>
		</table>
	</div>
</div>

app/views/admin/shoppings/process.js.erb
$("#shopping_<%=@shopping.id%>").replaceWith('<%= j(render "grid_ops",:shopping=>@shopping) %>');
$("#shopping_status_<%=@shopping.id%>").html("<%=@shopping.status%>")

app/views/admin/shoppings/show.html.erb
<%= content_for :title do %>
	订单详细信息 #<%=@shopping.id%>  
<% end %>

<%=render 'header_nav'%>

<div class=' box'>
	<div class='box-body'>
		<h2><strong>订单号:</strong>#<%= @shopping.id %></h2>
		
		<div class='pull-left'>
     </div>


		<div class='pull-right'>
			<%= link_to edit_admin_shopping_path(@shopping),:class=>"btn btn-info" do%>
				<i class="icon-edit"></i>	编辑订单
			<%end%>

     </div>
     <div class='clearfix'>

     </div>
     <hr class='hr-normal' />
			<h3><%=@shopping.status%></h3>
    

  		<table class='table table-hover'>
                   <thead>
									 	<tr>
											<th>商品名称</th>
											<th>订购数量</th>
											<th>单价</th>
											<th>小计</th>
                   	</tr>
                   </thead>
                   <tbody>
											<% @shopping.shopping_items.each do |item|%>
												<tr>

													<td><%=item.name%></td>
													<td><%=item.quantity%></td>
													<td>
														<div  class='text-center'><%=number_to_currency(item.price,:unit=>"&yen")%></div>
															</td>
													<td>
														<div  class='text-right'>
														<%=number_to_currency(item.amount,:unit=>"&yen")%>
														</div>
													</td>
												</tr>
											<%end%>
                   </tbody>
               </table>

               <div class='text-right'>
                   <h3 class='subtotal contrast'>  <%=number_to_currency(@shopping.amount,:unit=>"&yen") %></h3>
               </div>
               <hr class='hr-normal' />
               <div class='row-fluid'>
                   <div class='span4'>
                       <div class='lead'>
                      	<i class='icon-user contrast'></i>
                           客户信息
                       </div>
                   </div>
                   <div class='span7 offset1'>
                       <address>
                           <strong>客户姓名:</strong>
<a href="#" id="customer_name" data-type="text" data-pk="<%=@shopping.id%>" data-title="客户姓名">													 <%= @shopping.customer_name -%>
</a>
													<br/>
												 <abbr title='手机'>联系电话:</abbr>
												<a href="#" id="mobile" data-type="text" data-pk="<%=@shopping.id%>" data-title="联系电话">													  <%= @shopping.mobile -%>
                        
												</a>
                       </address>

                       <address>
												 <abbr title='手机'>客户地址:</abbr>
												<a href="#" id="customer_address" data-type="text" data-pk="<%=@shopping.id%>" data-title="客户地址">													  <%= @shopping.customer_address -%>
  											</a><br/>
												 <abbr title='预计收货时间'>预计收货时间:</abbr>
												<a href="#" id="want_ship" data-type="text" data-pk="<%=@shopping.id%>" data-title="预计收货时间">													  <%= @shopping.want_ship -%>
  											</a><br/>
													
													 <abbr title='下单时间'>下单时间:</abbr>
														<%= l @shopping.created_at%> </br>
                       </address>

                       <address>
                           <strong>备注信息
	                         </strong>
                           <br />
													<a href="#" id="remark" data-type="text" data-pk="<%=@shopping.id%>" data-title="订单备注">					<%= @shopping.remark -%>
													</a>
                       </address>

                   </div>
               </div>


               <div class='row-fluid'>
                   <div class='span4'>
                       <div class='lead'>
                           <i class='icon-book contrast'></i>
                           订单其他信息
                       </div>
                   </div>
                   <div class='span7 offset1'>

                   </div>
               </div>

           </div>

       </div>
				<%=render 'operation_buttons'%>

   </div>

<script>
	$.fn.editable.defaults.mode=  'inline' ;
	$.fn.editable.defaults.ajaxOptions = {type: "PUT"}
	$('#customer_name').editable({
	    type: 'text',
	    name: 'customer_name',
	    pk: '<%=@shopping.id%>',
	    url: '/admin/shoppings/<%=@shopping.id%>/update_field'
	});

	$('#remark').editable({
	    type: 'text',
	    name: 'remark',
	    pk: '<%=@shopping.id%>',
	    url: '/admin/shoppings/<%=@shopping.id%>/update_field'
	});

	$('#want_ship').editable({
	    type: 'text',
	    name: 'want_ship',
	    pk: '<%=@shopping.id%>',
	    url: '/admin/shoppings/<%=@shopping.id%>/update_field'
	});
	$('#mobile').editable({
	    type: 'text',
	    name: 'mobile',
	    pk: '<%=@shopping.id%>',
	    url: '/admin/shoppings/<%=@shopping.id%>/update_field'
	});
</script>