config/routes.rb
Usstfruit::Application.routes.draw do
  devise_for :users
  mount WeixinRailsMiddleware::Engine, at: "/"
  mount Usstfruit::API => "/"
  
  namespace :mobile do
    root :to => 'products#index'
    get "two",:controller=>:home,:action=>:test
    resources :products
    resources :articles
    
    #shopping part
    resources :carts
    resources :cart_items do
      collection do
        get 'plus'
        get 'minus'
      end
    end
    resources :shoppings
    resources :weixin_users do
      member do 
        get 'history_shopping'
      end
    end
    
 end
 
 namespace :admin do
   root :to => 'home#index'
   
   resources :weixin_users
   
   resources :products do
     member do
       get 'on_sale'
       get 'off_sale'
     end
   end
   
   resources :product_cates
   resources :shoppings do
     member do
       get 'to_cancel'
       get 'to_confirm'
       get 'to_ship'
       get 'to_finish'
       
       get 'operation_history'
       
       put 'update_field'
       
       
       get 'daily_result'
     end
   end
   
   resources :articles
   resources :article_cates
   resources :users
   
   resources :pictures do
     collection do
       post 'upload'
     end
   end
 end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :weixin_user
  has_many :cart_items
  
  
  def total_count
    self.cart_items.inject(0) { |sum, i| sum+i.quantity }
  end
  
  def total_amount
    self.cart_items.inject(0) { |sum, i| sum+i.amount }
  end
  
  def check_any_off_sale?
    result = false
    self.cart_items.each do |cart_item|
       unless cart_item.product.on_sale?
         cart_item.destroy
         result = true
       end
    end
    result
  end
  
  def add_item(item)
    puts "id is #{item.product_id}"
    current_item = cart_items.find_by_product_id(item.product_id)    
    if current_item
      current_item.quantity+=item.quantity
      puts current_item.to_json
    else
      current_item = item
      item.cart = self
    end
    current_item.cal_amount
    current_item
  end
end

app/controllers/mobile/articles_controller.rb
class Mobile::ArticlesController <  Mobile::BaseController
  layout "mobile_article"
  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/mobile/base_controller.rb
class Mobile::BaseController < ApplicationController
  layout "mobile"
  before_filter :set_current_weixin_user
  
  def set_current_weixin_user
    if params[:weichat_id].present?
      @user = WeixinUser.find_by_open_id(params[:weichat_id])
      if @user
        session[:weixin_user_id] = @user.id
      else
        @user = WeixinUser.new
        @user.open_id =  params[:weichat_id]
        @user.save
        session[:weixin_user_id] = @user.id
      end
    end
  end
  
  def current_weixin_user_id
    session[:weixin_user_id]
  end
  
  
  def current_cart
    Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart=Cart.create
    session[:cart_id]=cart.id
    cart
  end
  
  
end

app/controllers/mobile/cart_items_controller.rb
class Mobile::CartItemsController < Mobile::BaseController
  def create
    if params[:cart_item][:quantity].present? && params[:cart_item][:product_id].to_i > 0
      @cart_item = CartItem.new(cart_item_params)
      @product = Product.find(@cart_item.product_id)
      if @product.on_sale == false
        @success = false
      end
      
      @cart_item.build_with_product(@product)
      @cart_item.quantity = params[:cart_item][:quantity]
      @cart_item = current_cart.add_item(@cart_item)
      @success = @cart_item.save
    else
       @success =false
    end
  end
  
  def destroy
    @success = false
    @cart_item = CartItem.find(params[:id])
    @success = @cart_item.destroy
  end
  
  
  def plus
    @success = false
    
    if params[:cart_id].present? & params[:product_id].present?
      @cart = Cart.find(params[:cart_id])
      @product = Product.find(params[:product_id])
      @cart_item = @cart.cart_items.find_by_product_id(params[:product_id])
      if @cart_item.nil?
        @product = Product.find(params[:product_id])
        @cart_item = CartItem.new
        @cart_item.product_id = @product.id
        @cart_item.cart_id = @cart.id
        
        @cart_item.no = @product.no
        @cart_item.name = @product.name
        @cart_item.point = @product.point
        @cart_item.price = @product.price
      else
        @cart_item.price =  @product.price
      end
      
      @cart_item.quantity = @cart_item.quantity.to_i + 1
      @cart_item.amount = @cart_item.quantity  * @cart_item.price
      @cart_item.save
    end
    
    

  end
  
  def minus
    @success = false
    if params[:cart_id].present? & params[:product_id].present?
      @cart = Cart.find(params[:cart_id])
      @product = Product.find(params[:product_id])
      @cart_item = @cart.cart_items.find_by_product_id(params[:product_id])
      if @cart_item
        @cart_item.price =  @product.price
        @cart_item.quantity = @cart_item.quantity.to_i - 1
        @cart_item.amount = @cart_item.quantity  * @cart_item.price
        @cart_item.save
      end
    end
  end
  
  
  
  private 
  
  def cart_item_params
    params.require(:cart_item).permit!
  end
  
end

app/controllers/mobile/carts_controller.rb
class Mobile::CartsController < Mobile::BaseController
  def show
    @cart = Cart.find(params[:id])
  end

  def edit
    @cart = Cart.find(params[:id])
  end
  
  
  def update
    @cart = Cart.find(params[:id])
    if @cart.total_count < 1
      redirect_to edit_mobile_cart_path(@cart)
      return
    end

    if @cart.update(cart_params)
      redirect_to new_mobile_shopping_path(:cart_id=>@cart)
    end
  end
  
  private
  def cart_params
    params.require(:cart).permit!
  end
end

app/controllers/mobile/home_controller.rb
class  Mobile::HomeController < Mobile::BaseController  
    def index
    end
    
    def test
      
    end
end

app/controllers/mobile/products_controller.rb
class  Mobile::ProductsController < Mobile::BaseController  
  def index
    @product_cates = ProductCate.all.order("priority desc")
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
end

app/controllers/mobile/shoppings_controller.rb
class  Mobile::ShoppingsController < Mobile::BaseController  
  def index
  end
  
  def show
    @shopping = Shopping.find(params[:id])
  end
  
  def create
    @shopping = Shopping.new(shopping_params)
    
    logger.info("new shopping from cart id :#{@shopping.cart_id}")
    @cart = Cart.find(@shopping.cart_id)
    
    @cart.cart_items.each do |cart_item|
      if cart_item.quantity > 0 && cart_item.product.on_sale?
        shopping_item = ShoppingItem.new
        shopping_item.product_id = cart_item.product_id
        shopping_item.no  = cart_item.no
        shopping_item.name  = cart_item.name
        shopping_item.price  = cart_item.price
        shopping_item.unit = cart_item.try(:product).try(:unit)
        shopping_item.quantity  = cart_item.quantity
        shopping_item.amount  = cart_item.amount
        @shopping.shopping_items << shopping_item
      end
    end
    @shopping.cal_amount
    @shopping.weixin_user_id = current_weixin_user_id
    if @shopping.save
      session[:cart_id]=nil
      redirect_to history_shopping_mobile_weixin_user_path(current_weixin_user_id)
    else
      render 'new'
    end
  end
  
  
  def new
    if params[:cart_id].present? 
      @shopping = Shopping.new
      @shopping.cart_id = params[:cart_id]
      
      @cart = Cart.find(@shopping.cart_id)
      
      if @cart.check_any_off_sale?
        redirect_to edit_mobile_cart_path(@cart)
      end
      
      @shopping.remark = @cart.remark

    else
      redirect_to mobile_products_path
    end
  end
  
  private
  def shopping_params
    params.require(:shopping).permit!
  end
end

app/controllers/mobile/weixin_users_controller.rb
class  Mobile::WeixinUsersController < Mobile::BaseController  
  def index
    
  end
  
  def show
    @weixin_user = WeixinUser.find(params[:id])
  end
  
  def history_shopping
    @weixin_user = WeixinUser.find(params[:id])
    @shoppings = Shopping.where("weixin_user_id = ?",@weixin_user.id).order("created_at desc")
  end

end

app/views/mobile/carts/_cart_item.html.erb
<%product = cart_item.product%>


<div id="prodcut_<%=product.id%>" class="product">
	<div id="product_image_<%=product.id%>" class="product_image">
		<%=link_to [:mobile,product],:remote=>true,"data-ignore"=>"push" do%>
			<%=image_tag product.cover_url(:small) ,:class=>"product_cover"%>
		<%end%>
	</div>
	<div class="product_content">
		<h3><%=product.name%> 
			<%if not product.on_sale?%>
			<small>
				[已下架]
			</small>
			<%end%>
		</h3>
		
		<div class="product_detail">
			<div class="product_price">
				<span class="price"><%=number_to_currency product.price,:unit=>"&yen"%></span><span class="unit">/<%=product.unit%></span>
			</div>
			<div class="product_button pull-right">
				<%quantity = current_cart.cart_items.find_by_product_id(product.id).try(:quantity)%>
				<%quantity = quantity.nil? ? 0 : quantity%>
				
				<%=link_to minus_mobile_cart_items_path(:cart_id=>current_cart,:product_id=>product.id) ,:remote=>true,"data-ignore"=>"push" do%>
				<i class="fa fa-minus-circle grey"></i>
				<%end%>
				<p class="product_quantity"><%=quantity%></p>
				<%=link_to plus_mobile_cart_items_path(:cart_id=>current_cart,:product_id=>product.id) ,:remote=>true,"data-ignore"=>"push" do%>
					<i class="fa fa-plus-circle red"></i>
				<%end%>
			</div>
		</div>
	</div>
</div>

<script>
	<%if quantity == 0%>
	$("#prodcut_<%=product.id%> .fa-minus-circle").hide();
	$("#prodcut_<%=product.id%> .product_quantity").hide();	<%end%>
</script>

app/views/mobile/carts/_cart_item_list.html.erb
<ul class="table-view roll-y" style="margin-top:0px">	
		<%@cart.cart_items.each do |cart_item|%>
			<%if cart_item.quantity > 0 %>		
				<li class="table-view-cell">
					<%=render 'cart_item',:cart_item=>cart_item%>
				</li>
			<%end%>
		<%end%>
		<li class="table-view-cell" style="background-color:#FBE9E9;font-size:14px">
			<span id="total_count">已选 <%=current_cart.try(:total_count)%> 件</span>
			<span id="total_amount">总计  <%=current_cart.try(:total_amount)%> 元</span>
		</li>
		
		
		<li class="table-view-cell" style="padding:0px" >		
			<%=simple_form_for [:mobile,@cart] ,:html=>{:class=>"input-group"} do |f| %>
			  <div class="input-row">
			    <label>订单备注</label>
					<%=f.text_field :remark,:placeholder=>"比如特殊的送货时间或者水果要求"%>
			  </div>
			<%end%>
		</li>
</ul>


<button class="btn btn-block submit-cart">去结算</button>

<script>
	$(document).ready(function(){
	  $(".submit-cart").click(function(){
			$("form.input-group").submit();
	  });
	});
</script>

app/views/mobile/carts/edit.html.erb
<%=render 'cart_item_list'%>