config/routes.rb
Usstfruit::Application.routes.draw do
  devise_for :users
  mount WeixinRailsMiddleware::Engine, at: "/"
  mount Usstfruit::API => "/"
  
  namespace :mobile do
    root :to => 'products#index'
    get "two",:controller=>:home,:action=>:test
    resources :products
    resources :articles
    
    #shopping part
    resources :carts
    resources :cart_items do
      collection do
        get 'plus'
        get 'minus'
      end
    end
    resources :shoppings
    resources :weixin_users do
      member do 
        get 'history_shopping'
      end
    end
    
 end
 
 namespace :admin do
   root :to => 'home#index'
   
   resources :weixin_users
   
   resources :products do
     member do
       get 'on_sale'
       get 'off_sale'
     end
   end
   
   resources :product_cates
   resources :shoppings do
     member do
       get 'to_cancel'
       get 'to_confirm'
       get 'to_ship'
       get 'to_finish'
       
       get 'operation_history'
       
       put 'update_field'
       
       
       get 'daily_result'
     end
   end
   
   resources :articles
   resources :article_cates
   resources :users
   
   resources :pictures do
     collection do
       post 'upload'
     end
   end
 end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :article_cate
  validates :title,:presence => true
  mount_uploader :cover, ArticleCoverUploader
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController <  Admin::BaseController
  def index
    @q = Article.search(params[:q])
    @articles = @q.result(distinct: true)
    @articles_grid = initialize_grid(@articles,:per_page => 20)
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to [:admin,@article],:notice=>"新建文章成功!"
    else
      render 'new'
    end
  end
  
  def edit
    @article = Article.find(params[:id]) 
  end
  
  def update
    @article = Article.find(params[:id]) 
    if @article.update(article_params)
      redirect_to [:admin,@article],:notice=>"更新文章成功"
    else
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id]) 
    @article.destroy
    redirect_to admin_articles_path
  end
  
  private
  def article_params
    params.require(:article).permit!
  end
end

app/controllers/mobile/articles_controller.rb
class Mobile::ArticlesController <  Mobile::BaseController
  layout "mobile_article"
  def show
    @article = Article.find(params[:id])
  end
end

app/views/admin/articles/_form.html.erb
<%=render 'shared/error_messages',:target=>@article%>

<%=simple_form_for([:admin,@article],:html=>{:class=>"form-horizontal"}) do |f|%>
	<%= f.input :title,:input_html=>{:class=>"form-control"}%>
	<%= f.input :keywords,:input_html=>{:class=>"form-control"}%>	
	<%= f.input :breif,:input_html=>{:class=>"form-control"}%>	
	<%= f.input :article_cate_id,:collection=>ArticleCate.all,:label_method=>:name,:value_method=>:id,:input_html=>{:class=>"form-control"}%>	
	
	<%= f.input :cover%>
	
	<%= f.input :hidden,:input_html=>{:class=>"form-control"}%>
	<%= f.input :content%>
	
	<div class="form-actions">
		<%=link_to "返回列表", admin_articles_path,:class=>"btn"%>
		<button type="submit" class="btn btn-primary pull-right">保存</button> 
	</div> <!-- /form-actions -->
<%end%>
<script type="text/javascript">
$(document).ready(function(){
	var editor = new Simditor({
	  textarea: $('#article_content'),
	  toolbar:[
		  'title' ,
		  'bold'   ,
		  'italic' ,
		  'underline'  ,
		  'strikethrough' ,
		  'ol'  ,
		  'ul'   ,
		  'blockquote' ,
		  'table'    ,
		  'link'      ,
		  'image' ,
		
		  'hr'      ,       
		  'indent'  ,      
		  'outdent'  
			],
		 defaultImage: '/images/logo.jpg',
		 pasteImage: true,
		 upload:{
		   'url': '/admin/pictures/upload',
		   'params': {'module':"article"},
		   'connectionCount': 1,
		   'leaveConfirm': '正在上传文件，如果离开上传会自动取消'}
	});
});

</script>

app/views/admin/articles/_grid.html.erb
<%= grid(@articles_grid, show_filters: :when_filtered, hide_csv_button: true) do |g|
	g.column :name => 'ID', :attribute => 'id'
	
	g.column :name => '标题', :attribute => 'title'  do |article|
		link_to article.title,[:admin,article]
	end
	g.column :name => '分类', :attribute => 'article_cate_id'  do |article|
		if article.article_cate
			link_to article.article_cate.name,[:admin,article.article_cate] 
		end
	end


	g.column :name => "关键字" ,:attribute => "keywords"
	g.column :name => "发布",:attribute => "hidden" do |article|
		t article.hidden.to_s
	end

	g.column do |article|
		edit =  link_to raw("<button class=\"btn btn-mini btn-info\"><i class=\"fa fa-edit bigger-120\"></i></button>"), edit_admin_article_path(article)
		remove = link_to raw("<button class=\"btn btn-mini btn-danger\"><i class=\"fa fa-trash-o bigger-120\"></i></button>"), [:admin,article], method: :delete, data: { confirm: 'Are you sure?' }
		raw "#{edit} #{remove}"
	end
	
end -%>

app/views/admin/articles/edit.html.erb
<div class="box">
	<div class="box-header">
	   <h3 class="box-title">编辑文章</h3>
		 <div class="box-tools">

     </div>
	</div><!-- /.box-header -->
	<div class="box-body">
		<%=render 'form'%>
	</div>
</div>

app/views/admin/articles/index.html.erb
<div class="box">
	<div class="box-header">
	   <h3 class="box-title">文章列表</h3>
		 <div class="box-tools">
		 	<ul class="pagination pagination-sm no-margin pull-right">
       <li>
       	<%=link_to new_admin_article_path do%>
					<i class="fa fa-plus">新建</i>
				<%end%>
       </li>
     	</ul>
     </div>
	</div><!-- /.box-header -->
	<div class="box-body">
		<%=render 'grid'%>
	</div>
</div>

app/views/admin/articles/new.html.erb
<div class="box">
	<div class="box-header">
	   <h3 class="box-title">新建文章</h3>
		 <div class="box-tools">

     </div>
	</div><!-- /.box-header -->
	<div class="box-body">
		<%=render 'form'%>
	</div>
</div>

app/views/admin/articles/show.html.erb
<%= content_for :title do %>
	文章明细
<% end %>
<div class="box">
	<div class="box-header">
	   <h3 class="box-title">标题-<%=@article.title%>
     </h3>

	</div><!-- /.box-header -->
	<div class="box-body">
    <div class="row">
        <div class="col-md-4">
					<strong>微信用连接:</strong><br/>
					<i><%="#{mobile_article_url(@article)}"%></i><br/>
					<strong>关键字:</strong><br/>
					<i><%=@article.keywords%></i>
				</div>
				
        <div class="col-md-8">
					<%=raw @article.content%>
				</div>	
				
		
			</div>
			
		<div class="row">
			<hr/>
			<div class="btn-group pull-right">
				<%=link_to "编辑",edit_admin_article_path(@article),:class=>"btn"%>
				<%=link_to "删除",[:admin,@article],:method=>:delete,:class=>"btn btn-danger"%>
			</div>
		</div>
	</div>
</div>