config/routes.rb
Usstfruit::Application.routes.draw do
  devise_for :users
  mount WeixinRailsMiddleware::Engine, at: "/"
  mount Usstfruit::API => "/"
  
  namespace :mobile do
    root :to => 'products#index'
    get "two",:controller=>:home,:action=>:test
    resources :products
    resources :articles
    
    #shopping part
    resources :carts
    resources :cart_items do
      collection do
        get 'plus'
        get 'minus'
      end
    end
    resources :shoppings
    resources :weixin_users do
      member do 
        get 'history_shopping'
      end
    end
    
 end
 
 namespace :admin do
   root :to => 'home#index'
   
   resources :weixin_users
   
   resources :products do
     member do
       get 'on_sale'
       get 'off_sale'
     end
   end
   
   resources :product_cates
   resources :shoppings do
     member do
       get 'to_cancel'
       get 'to_confirm'
       get 'to_ship'
       get 'to_finish'
       
       get 'operation_history'
       
       put 'update_field'
       
       
       get 'daily_result'
     end
   end
   
   resources :articles
   resources :article_cates
   resources :users
   
   resources :pictures do
     collection do
       post 'upload'
     end
   end
 end
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :product_cate
  mount_uploader :cover, ProductCoverUploader
  
  scope :can_sale, -> { where(on_sale: true) }
  
  def sale?
    self.on_sale
  end
  
  def change_on_sale
    self.on_sale = true
  end
  
  def change_off_sale
    self.on_sale = false
  end
end

app/controllers/admin/products_controller.rb
class  Admin::ProductsController < Admin::BaseController  
  def index
    @q = Product.search(params[:q])
    @products = @q.result(distinct: true).order("priority desc")
    @products_grid = initialize_grid(@products,:per_page => 20)
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product),:notice=>"新建商品成功"
    else
      render 'new'
    end
  end
  
  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(@product),:notice=>"更新商品种功"
    else
      redirect_to 'edit'
    end
  end
  
  def on_sale
    @product = Product.find(params[:id])
    if @product.on_sale?
      @success = false
    else
      @product.change_on_sale
      @success = @product.save
    end
  end
  
  def off_sale
    @product = Product.find(params[:id])
    if @product.on_sale?  
      @product.change_off_sale
      @success = @product.save
    else
      @success = false
    end
  end
  
  private
  def product_params
    params.require(:product).permit!
  end
end

app/controllers/mobile/products_controller.rb
class  Mobile::ProductsController < Mobile::BaseController  
  def index
    @product_cates = ProductCate.all.order("priority desc")
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
end

app/views/admin/products/_form.html.erb
<%=render 'shared/error_messages',:target=>@product%>

<%=simple_form_for([:admin,@product],:html=>{:class=>"form-horizontal"}) do |f|%>
<fieldset>
	<div class="row">
    <div class="col-md-3">
        <div class='lead'>
            <i class='icon-th-large text-contrast'></i>
            总库商品信息
        </div>
				<%=image_tag @product.cover_url(:normal)%>
    </div>
    <div class="col-md-9">
			<%=f.input :name,:input_html=>{:class=>"form-control"}%>
			<%=f.input :no,:input_html=>{:class=>"form-control"}%>
			<%=f.input :cover%>
			<%= f.input(:product_cate_id, :collection => ProductCate.all,
			       :label_method => :name,
			       :value_method  => :id,
			       :include_blank => "选择商品分类")%>
			
			<%=f.input :mk_price,:input_html=>{:class=>"form-control"}%>
			<%=f.input :price,:input_html=>{:class=>"form-control"}%>	
			<%=f.input :unit,:input_html=>{:class=>"form-control"}%>
			<%= f.input :on_sale,:html=>{:class=>"form-control"},:collection=>[["上架",1],["下架",0]],:include_blank=>false%>
				
				
			<%=f.input :priority,:input_html=>{:class=>"form-control"}%>
			
			<%=f.input :keywords,:placeholder=>"多个关键字用空分开",:input_html=>{:class=>"form-control"}%>
			<%=f.input :brief,:input_html=>{:class=>"form-control"}%>
			<%=f.input :content%>	

		</div>

	</fieldset>
		<div class="form-actions">
			<%=link_to "返回列表", admin_products_path,:class=>"btn"%>
			<button type="submit" class="btn btn-primary pull-right">保存</button> 
			
		</div> <!-- /form-actions -->
<%end%>

<script type="text/javascript">
$(document).ready(function(){
	var editor = new Simditor({
	  textarea: $('#product_content'),
	  toolbar:[
		  'title' ,
		  'bold'   ,
		  'italic' ,
		  'underline'  ,
		  'strikethrough' ,
		  'ol'  ,
		  'ul'   ,
		  'blockquote' ,
		  'table'    ,
		  'link'      ,
		  'image'
			],
		 defaultImage: '/images/logo.png',
		 pasteImage: true,
		 upload:{
		   'url': '/admin/pictures/upload',
		   'params': {'module':"product"},
		   'connectionCount': 1,
		   'leaveConfirm': '正在上传文件，如果离开上传会自动取消'}
	});
});
</script>

app/views/admin/products/_grid.html.erb
<%= grid(@products_grid, show_filters: :when_filtered, hide_csv_button: true) do |g|
	g.column :name => '名称', :attribute => 'name' do |product|
		link_to product.name,[:admin,product]
	end
	g.column :name => '编号', :attribute => 'no'
	
	g.column :name => "种类", :attribute => "name",:model=>"ProductCate" do |product|
		
  end

	g.column :name => "销售价",:attribute => "price"
	
	g.column :name => "市场价",:attribute => "mk_price"
	

	g.column :name => "显示权重" ,:attribute => "priority" do |product|
		product.priority
	end
	
	g.column :name => "上架" ,:attribute => "on_sale" do |product|
		render "grid_on_sale",:product=>product
	end 
	
	g.column do |product|
		
		edit =  link_to raw("<button class=\"btn btn-mini btn-info\"><i class=\"fa fa-edit \"></i></button>"), edit_admin_product_path(product)
		remove = link_to raw("<button class=\"btn btn-mini btn-danger\"><i class=\"fa fa-trash-o \"></i></button>"), [:admin,product], method: :delete, data: { confirm: '确定删除吗?' }
		raw "#{edit} #{remove}"
	end
end -%>

app/views/admin/products/_grid_on_sale.html.erb
<div id="product<%=product.id%>" >  
	<%if product.on_sale?%>
		<%= link_to "#{t product.on_sale.to_s}",off_sale_admin_product_path(product),:remote=>true%>
	
	<%else%>
		<%= link_to "#{t product.on_sale.to_s}",on_sale_admin_product_path(product),:remote=>true%>
	<%end%>
</div>

app/views/admin/products/edit.html.erb
<div class="box">
	<div class="box-header">
	   <h3 class="box-title">编辑商品</h3>
		 <div class="box-tools">

     </div>
	</div><!-- /.box-header -->
	<div class="box-body">
		<%=render 'form'%>
	</div>
</div>

app/views/admin/products/index.html.erb
<div class="box">
	<div class="box-header">
	   <h3 class="box-title">商品列表</h3>
		 <div class="box-tools">
		 	<ul class="pagination pagination-sm no-margin pull-right">
       <li>
       	<%=link_to new_admin_product_path do%>
					<i class="fa fa-plus">新建</i>
				<%end%>
       </li>
     	</ul>
     </div>
	</div><!-- /.box-header -->
	<div class="box-body">
		<%=render 'grid'%>
	</div>
</div>

app/views/admin/products/new.html.erb
<div class="box">
	<div class="box-header">
	   <h3 class="box-title">新建商品</h3>
		 <div class="box-tools">

     </div>
	</div><!-- /.box-header -->
	<div class="box-body">
		<%=render 'form'%>
	</div>
</div>

app/views/admin/products/off_sale.js.erb
$("#product<%=@product.id%>").replaceWith('<%= j(render "grid_on_sale",:product=>@product) %>');

app/views/admin/products/on_sale.js.erb
$("#product<%=@product.id%>").replaceWith('<%= j(render "grid_on_sale",:product=>@product) %>');

app/views/admin/products/show.html.erb
<div class='box bordered-box blue-border'>

  <div class='box-header blue-background'>
	  <div class='title'>
        <i class='icon-th-large'></i>
        商品信息-<%=@product.name%>
    </div>
	</div> <!-- /widget-header -->		
  <div class='box-body box-double-padding'>
		<div class="row">
	    <div class="col-md-4">
					<%=image_tag @product.cover_url(:normal)%>
			</div>
	    <div class="col-md-8">
				<b>商品名称:</b><%=@product.name%><br/>
				<b>编号:</b><%=@product.no%><br/>
				<b>分类:</b><%="#{@product.try(:product_cate).try(:name)}"
				%><br/>
				
				<b>市场价:</b><%=number_to_currency(@product.mk_price,:unit=>"&yen")%><br/>
				<b>出售价:</b><%=number_to_currency(@product.price,:unit=>"&yen")%><br/>
				<b>计量单位:</b><%=@product.unit%><br/>
				
				<b>商品简介:</b><%=@product.brief%><br/>
				<b>商品文字详细介绍:</b><hr/>
				<%=raw @product.content%>
			
			</div>
			</div>
		</div>
</div>
	<div class="row">
		<div class="btn-group pull-left">						
			<%=link_to "返回列表",admin_products_path,:class=>"btn"%>

		</div>

		<div class="btn-group pull-right">
			<%=link_to "编辑",edit_admin_product_path(@product),:class=>"btn"%>
			<%=link_to "删除",[:admin,@product],:method=>:delete,:class=>"btn btn-danger"%>
		</div>
	</div>
	